### ISSUE TITLE
Adding this library to a typescript project causes compilations error: `TS2304: Cannot find name 'Long'`

### ISSUE THREAD

**Issue by gae123** [googleapis/nodejs-logging#604]
Steps to reproduce:

1. Create a small typescript project that compiles and works
1. In package.json  add `"@google-cloud/logging": "5.4.1"`
1. Import with `import * as googleLogging from '@google-cloud/logging';`
1. Compile again, you will now see errors about missing Long

### WORKAROUND
I did what I describe [here](https://stackoverflow.com/questions/58159115) to work around this issue, but this should not be required or at least should be documented.

**Environment**
```
$ tsc --version
Version 3.5.3
$ node --version
v10.16.2
```

**Comment by JustinBeckwith** [comment]
Greetings folks!  I'm having a little trouble reproducing this one.  Here is the example I'm working from:
https://github.com/JustinBeckwith/ts2304

Could I ask you to:
- Try the latest version of TypeScript (3.7.2 as of now)
- Try the latest version of `@google-cloud/logging` (5.5.4 as of now)
- Try running `rm -rf node_modules package-lock.json`, and running `npm install` again.  

I suspect some older versions of `protobufjs` are getting cached, as I think we fixed this way back here:
https://github.com/protobufjs/protobuf.js/pull/1166

**Comment by fallard84** [comment]
I have the same issue. The fix https://github.com/protobufjs/protobuf.js/pull/1166 is still not released.

**Comment by bcoe** [comment]
@alexander-fenster I noticed we'd landed the long type in gax, does this address the issue in this thread?

**Comment by alexander-fenster** [comment]
@bcoe No, because this project has its own hand crafted `.d.ts` files. I'm fixing it in a separate PR (linked above).
